on:
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  push:
    branches:
      - main
      - golang-alpha
  pull_request:
      types: [opened, synchronize, reopened]

name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - uses: actions/setup-go@v4
    - run: go install
    - run: go build
    - run: go test
    - run: staticcheck