on:
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  push:
    branches:
      - main
      - golang-alpha
  pull_request:
      types: [opened, synchronize, reopened]

name: Main Workflow
jobs:
  sonarqube:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - uses: actions/setup-go@v4
    - run: go install
    - run: go build
    - run: go test -json > test-report.out
    - run: go test -coverprofile='coverage.out'
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        args: >
          -Dsonar.projectKey=oxcafedead_barcode-reader-emulator
          -Dsonar.organization=oxcafedead
          -Dsonar.go.tests.reportPaths=test-report.out
          -Dsonar.go.coverage.reportPaths=coverage.out
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}